info:
  contact: {}
  license: {}
paths:
  /limit/randomreject:
    get:
      parameters:
      - description: 参数描述
        in: query
        name: 无
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功会返回ok
          schema:
            type: string
        "502":
          description: 失败返回reject
      summary: 随机拒流
      tags:
      - limit
  /ping:
    get:
      description: ping接口，用于测试是否调通
      parameters:
      - description: 参数描述
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 接口探活
      tags:
      - base
swagger: "2.0"
